services:
  airflow:
    build: .
    container_name: airflow

    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./app:/opt/airflow/app
      - ./data:/data

    ports:
      - "127.0.0.1:8080:8080"

    # command:
    #   - bash
    #   - -c
    #   - |
    #       airflow db migrate &&
    #       airflow users create \
    #         --username admin \
    #         --password admin \
    #         --firstname admin \
    #         --lastname admin \
    #         --role Admin \
    #         --email admin@example.com &&
    #       airflow scheduler & airflow webserver
    command:
      - bash
      - -c
      - |
          airflow db migrate
          airflow users create \
            --username admin \
            --password admin \
            --firstname admin \
            --lastname admin \
            --role Admin \
            --email admin@example.com || true
          airflow scheduler &
          exec airflow webserver

